name: Run mypy and ruff

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: github-actions-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Run ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y ffmpeg
      
      - name: Run dependency libraries
        run: |
          pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 torchtext==0.15.1
          pip install ftfy regex tqdm
          pip install 'clip@git+https://github.com/openai/CLIP.git'
          pip install mypy ruff
      
      - name: Run mypy
        run: mypy firefly

      - name: Run ruff
        run: ruff check firefly
